# SERVER='https://acme-v02.api.letsencrypt.org/directory'
SERVER='https://acme-staging-v02.api.letsencrypt.org/directory'
RESOLVERS=('8.8.8.8:53' '77.88.8.8:53' '1.1.1.1:53')
DNS='cloudflare'
MAIL_ON=0
MAIL_FROM='postmaster@example.org'
MAIL_TO=('mail@example.org')
GITLAB_ON=0
GITLAB_API='http://example.org/api/v4'
GITLAB_PROJECT='0'
GITLAB_TOKEN='TOKEN'
