name: ''
description: ''
install:
  files:
    - name: 'app.acme.yml'
      path: '/root/apps/acme'
    - name: 'app.hook.deploy.conf'
      path: '/root/apps/acme'
    - name: 'app.hook.deploy.sh'
      path: '/root/apps/acme'
    - name: 'job.acme'
      path: '/root/apps/acme'
